pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t flask-app -f docker/Dockerfile .'
            }
        }
        stage('Run') {
            steps {
                sh 'docker-compose -f docker/docker-compose.prod.yml up -d'
            }
        }
    }
}
